service: travel-project

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs20.x
  architecture: x86_64
  timeout: 15
  httpApi:
    payload: "1.0"
    disableDefaultEndpoint: false
  environment:
    DATABASE_URL: ${ssm:/DATABASE_URL}
    NODE_OPTIONS: "--enable-source-maps"

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "src/domain/*/serverless/handler"
    - "node_modules/**"
    - "node_modules/prisma/**"
    - "node_modules/@prisma/**"
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    watch:
      pattern: "src/**/*.ts"

functions:
  - ${file(./src/domain/plan-category/serverless/functions.yml)}
